### ISSUE TITLE
Permissions for the plot_example

### ISSUE THREAD

**Issue by mitchute** [Myoldmopar/MyPyOpt#22]
Ran the plot_example case on my Windows laptop. The following is the result.

```
E:\Dropbox\MyPyOpt\demos\plot_example>python main.py
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    a = MyApp(None)
  File "main.py", line 73, in __init__
    searcher = HeuristicSearch(sim, dvs, io, sim_quadratic, ssqe_quadratic, prog
ress)
  File "E:\Dropbox\MyPyOpt\demos\plot_example\../..\mypyopt\OptimizerHeuristicSe
arch.py", line 43, in __init__
    raise MyPyOptException("Couldn't create project folder, check permissions, a
borting...")
mypyopt.Exceptions.MyPyOptException: Couldn't create project folder, check permi
ssions, aborting...
Fatal Python error: PyEval_RestoreThread: NULL tstate

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

My GHX project runs on my dropbox and I create folders all of the time, so that seemed strange.

**Comment by mitchute** [comment]
```
E:\Dropbox\MyPyOpt\demos\pretend_energyplus>dir
 Volume in drive E is Shared
 Volume Serial Number is 544A-52D6

 Directory of E:\Dropbox\MyPyOpt\demos\pretend_energyplus

12/01/2016  10:42 PM    <DIR>          .
12/01/2016  10:42 PM    <DIR>          ..
12/01/2016  10:42 PM             2,257 calibrate_walltemperatures.py
12/01/2016  10:42 PM               302 in_template.json
12/01/2016  10:42 PM               944 pretend_energyplus.py
12/01/2016  10:42 PM             1,675 README.md
               4 File(s)          5,178 bytes
               2 Dir(s)  56,692,867,072 bytes free

E:\Dropbox\MyPyOpt\demos\pretend_energyplus>python calibrate_walltemperatures.py

Traceback (most recent call last):
  File "calibrate_walltemperatures.py", line 53, in <module>
    searcher = HeuristicSearch(sim, dvs, io, sim_pretend_energyplus, ssqe_preten
d_energyplus)
  File "E:\Dropbox\MyPyOpt\demos\pretend_energyplus\../..\mypyopt\OptimizerHeuri
sticSearch.py", line 43, in __init__
    raise MyPyOptException("Couldn't create project folder, check permissions, a
borting...")
mypyopt.Exceptions.MyPyOptException: Couldn't create project folder, check permi
ssions, aborting...

E:\Dropbox\MyPyOpt\demos\pretend_energyplus>python
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.makedirs("test")
>>> quit()

E:\Dropbox\MyPyOpt\demos\pretend_energyplus>dir
 Volume in drive E is Shared
 Volume Serial Number is 544A-52D6

 Directory of E:\Dropbox\MyPyOpt\demos\pretend_energyplus

12/01/2016  10:52 PM    <DIR>          .
12/01/2016  10:52 PM    <DIR>          ..
12/01/2016  10:42 PM             2,257 calibrate_walltemperatures.py
12/01/2016  10:42 PM               302 in_template.json
12/01/2016  10:42 PM               944 pretend_energyplus.py
12/01/2016  10:51 PM    <DIR>          projects
12/01/2016  10:42 PM             1,675 README.md
12/01/2016  10:52 PM    <DIR>          test
               4 File(s)          5,178 bytes
               4 Dir(s)  56,692,867,072 bytes free
```

It looks like it is making the projects dir. I can also make the test dir without trouble.

**Comment by Myoldmopar** [comment]
It's the hardwired forward slash...I'll fix that up.

**Comment by Myoldmopar** [comment]
@mitchute I got this working now on my VM, let me know if you still see issues.
