### ISSUE TITLE
Windows...

### ISSUE THREAD

**Issue by mitchute** [Myoldmopar/MyPyOpt#27]
```
D:\Dropbox\MyPyOpt\demos\pretend_energyplus>python calibrate_walltemperatures.py

*******Optimization Beginning*******
Traceback (most recent call last):
  File "calibrate_walltemperatures.py", line 57, in <module>
    response = searcher.search()
  File "D:\Dropbox\MyPyOpt\demos\pretend_energyplus\..\..\mypyopt\OptimizerHeuristicSearch.py", line 100, in search
    obj_base = self.f_of_x(base_values)
  File "D:\Dropbox\MyPyOpt\demos\pretend_energyplus\..\..\mypyopt\OptimizerHeuristicSearch.py", line 203, in f_of_x
    simulation_results = self.callback_f_of_x(parameter_hash)
  File "calibrate_walltemperatures.py", line 26, in sim_pretend_energyplus
    str(resistance_value)], stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

**Comment by Myoldmopar** [comment]
Hmmmm I bet it's because on Windows it fails to execute the Python script directly.  I think if I changed the subprocess [call](https://github.com/Myoldmopar/MyPyOpt/blob/6435c786efb1265cdea1659243de0333a3d007e7/demos/pretend_energyplus/calibrate_walltemperatures.py#L25) from:

```
subprocess.call([os.path.join(this_dir, 'pretend_energyplus.py'),
```

to

```
subprocess.call(['python', os.path.join(this_dir, 'pretend_energyplus.py'), ...
```

assuming `python` is available on `$PATH`, it would work.  @mitchute would you mind trying that change?   I made the change and put it in the [Myoldmopar-Patch-1](https://github.com/Myoldmopar/MyPyOpt/pull/28) branch.

**Comment by mitchute** [comment]
Getting closer; at least it's running now. It make some successful iterations, then fails with the following.
```
iter=50
var=<mypyopt.DecisionVariable.DecisionVariable object at 0x022C5990>
x_base=[2.03236244737007, 19.9942940999502]
j_base=0.445896988695
x_new=[2.03236244737007, 19.97248311872069]
j_new=0.445997038962
## Unsuccessful objective evaluation, or worse result, going back ##
iter = 51
Traceback (most recent call last):
  File "calibrate_walltemperatures.py", line 57, in <module>
    response = searcher.search()
  File "D:\Dropbox\MyPyOpt\demos\pretend_energyplus\..\..\mypyopt\OptimizerHeuristicSearch.py", line 146, in search
    obj_new = self.f_of_x(new_values)
  File "D:\Dropbox\MyPyOpt\demos\pretend_energyplus\..\..\mypyopt\OptimizerHeuristicSearch.py", line 203, in f_of_x
    simulation_results = self.callback_f_of_x(parameter_hash)
  File "calibrate_walltemperatures.py", line 24, in sim_pretend_energyplus
    open(os.path.join(this_dir, 'in.json'), 'w').write(new_contents)
IOError: [Errno 22] invalid mode ('w') or filename: 'D:\\Dropbox\\MyPyOpt\\demos\\pretend_energyplus\\in.json'
```

**Comment by Myoldmopar** [comment]
Welp, that's super weird, because over here on Mac...

```
## Improved result, accepting and continuing forward ##
iter=95
var=<mypyopt.DecisionVariable.DecisionVariable object at 0x1034ab250>
x_base=[2.041123175381423, 19.984787505449443]
j_base=0.44586593563
x_new=[2.041123175381423, 19.984902612197114]
j_new=0.445865942726
## Unsuccessful objective evaluation, or worse result, going back ##
*******Converged*******
```

Oh.  It is failing in writing the json file?  Any chance it's having some issue with Dropbox/Sync?  Can you re-run and see if it fails on exactly the same iteration number?

**Comment by mitchute** [comment]
That's it. I paused syncing and it converges.

**Comment by Myoldmopar** [comment]
w00t!  OK cool, thanks for testing that man!!
